package trikita.slide;

public enum ActionType {
    SET_TEXT,

    OPEN_PRESENTATION,
    CLOSE_PRESENTATION,

    TOGGLE_TOOLBAR,

    SET_CURSOR,
    NEXT_PAGE,
    PREV_PAGE,

    PICK_IMAGE,
    INSERT_IMAGE,
    SET_COLOR_SCHEME,
    CREATE_PDF,
    EXPORT_PDF,

    CONFIGURE_PLANTUML,
    SET_TEMPLATE,
    PREVIOUS_PRESENTATION,
    NEXT_PRESENTATION,
    REMOVE_PRESENTATION, SET_PDF_RESOLUTION
}
